#!/bin/bash

# Script 5: Open Source Manifesto Generator
# Author: Sushanth Reddy

echo "----------------------------------------"
echo " Open Source Manifesto Generator"
echo "----------------------------------------"
echo ""

# Taking user input
read -p "1. Name one open-source tool you use daily: " TOOL
read -p "2. In one word, what does 'freedom' mean to you? " FREEDOM
read -p "3. What would you build and share freely? " BUILD

DATE=$(date '+%d %B %Y')
USER=$(whoami)
OUTPUT="manifesto_$USER.txt"

# Writing manifesto
echo "----------------------------------------" > $OUTPUT
echo " Open Source Manifesto" >> $OUTPUT
echo "----------------------------------------" >> $OUTPUT
echo "Date: $DATE" >> $OUTPUT
echo "" >> $OUTPUT

echo "I use $TOOL in my daily life, which shows the power of open-source software." >> $OUTPUT
echo "For me, freedom means $FREEDOM, and it allows innovation without restrictions." >> $OUTPUT
echo "In the future, I would like to build $BUILD and share it openly with the community." >> $OUTPUT
echo "I believe open source promotes collaboration, learning, and transparency." >> $OUTPUT

echo "" >> $OUTPUT
echo "Generated by $USER" >> $OUTPUT
echo "----------------------------------------" >> $OUTPUT

# Display output
echo ""
echo "Manifesto saved to $OUTPUT"
echo ""
cat $OUTPUT